### ISSUE TITLE
something is disappear

### ISSUE THREAD

**Issue by illsui1on** [soarsmu/Compressor#2]
train_data_file=../../../data/clone_detection/train_sampled.txt \  
where is train_sampled.txt？

**Comment by jiekeshi** [comment]
Hi @illsui1on, thanks for your issue. Sorry that is a typo in the documentation. Please use `train_data_file=../../../data/clone_detection/label_train.txt` instead. We have updated the corresponding README. 😊

**Comment by illsui1on** [comment]
thank you so much


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "soarsmu/Compressor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月27日(星期六) 下午3:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [soarsmu/Compressor] something is disappear (Issue #2)





 
Hi @illsui1on, thanks for your issue. Sorry that is a typo in the documentation. Please use train_data_file=../../../data/clone_detection/label_train.txt instead. We have updated the corresponding README. 😊

**Comment by jiekeshi** [comment]
I close this issue as we've solved it a long time ago.
